env:
  node: true
  commonjs: true
  es6: true
extends:
  - eslint:recommended
parserOptions:
  sourceType: module
  ecmaVersion: 7
  ecmaFeatures:
    impliedStrict: true
    globalReturn: true
rules:
  indent:
    - error
    - 2
    - SwitchCase: 1
  react/jsx-uses-react:
    - error
  react/jsx-uses-vars:
    - error
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  semi:
    - error
    - always
  no-extra-semi:
    - error
  no-console:
    - 0
